In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder

In [2]:
df=pd.read_csv("Datasets/train.csv")

In [3]:
df

survived  pclass                                               name  \
0           0       3                            Braund, Mr. Owen Harris   
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2           1       3                             Heikkinen, Miss. Laina   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4           0       3                           Allen, Mr. William Henry   
..        ...     ...                                                ...   
886         0       2                              Montvila, Rev. Juozas   
887         1       1                       Graham, Miss. Margaret Edith   
888         0       3           Johnston, Miss. Catherine Helen "Carrie"   
889         1       1                              Behr, Mr. Karl Howell   
890         0       3                                Dooley, Mr. Patrick   

        sex   age  sibsp  parch            ticket     fare cabin embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1    female  38.0      1      0          PC 17599  71.2833   C85        C  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    female  35.0      1      0            113803  53.1000  C123        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

store into new variable :

In [4]:
o=OrdinalEncoder(categories=[["male","female"]]) 

convert string into numeric :

In [5]:
o.fit_transform(df["sex"].values.reshape(-1,1)) 

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [6]:
o.fit_transform(df[["sex"]])  

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

direct store into actual data :

In [7]:
df["sex"]=o.fit_transform(df[["sex"]]) 

In [8]:
df

survived  pclass                                               name  sex  \
0           0       3                            Braund, Mr. Owen Harris  0.0   
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  1.0   
2           1       3                             Heikkinen, Miss. Laina  1.0   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  1.0   
4           0       3                           Allen, Mr. William Henry  0.0   
..        ...     ...                                                ...  ...   
886         0       2                              Montvila, Rev. Juozas  0.0   
887         1       1                       Graham, Miss. Margaret Edith  1.0   
888         0       3           Johnston, Miss. Catherine Helen "Carrie"  1.0   
889         1       1                              Behr, Mr. Karl Howell  0.0   
890         0       3                                Dooley, Mr. Patrick  0.0   

      age  sibsp  parch            ticket     fare cabin embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
1    38.0      1      0          PC 17599  71.2833   C85        C  
2    26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    35.0      1      0            113803  53.1000  C123        S  
4    35.0      0      0            373450   8.0500   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
886  27.0      0      0            211536  13.0000   NaN        S  
887  19.0      0      0            112053  30.0000   B42        S  
888   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889  26.0      0      0            111369  30.0000  C148        C  
890  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

conver float into int :

In [9]:
df["sex"]=df["sex"].astype(int)  

In [10]:
df

survived  pclass                                               name  sex  \
0           0       3                            Braund, Mr. Owen Harris    0   
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1   
2           1       3                             Heikkinen, Miss. Laina    1   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1   
4           0       3                           Allen, Mr. William Henry    0   
..        ...     ...                                                ...  ...   
886         0       2                              Montvila, Rev. Juozas    0   
887         1       1                       Graham, Miss. Margaret Edith    1   
888         0       3           Johnston, Miss. Catherine Helen "Carrie"    1   
889         1       1                              Behr, Mr. Karl Howell    0   
890         0       3                                Dooley, Mr. Patrick    0   

      age  sibsp  parch            ticket     fare cabin embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
1    38.0      1      0          PC 17599  71.2833   C85        C  
2    26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3    35.0      1      0            113803  53.1000  C123        S  
4    35.0      0      0            373450   8.0500   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
886  27.0      0      0            211536  13.0000   NaN        S  
887  19.0      0      0            112053  30.0000   B42        S  
888   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889  26.0      0      0            111369  30.0000  C148        C  
890  32.0      0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

how to do with pandas :

In [11]:
pd.get_dummies(df,columns=["embarked"]) 

survived  pclass                                               name  sex  \
0           0       3                            Braund, Mr. Owen Harris    0   
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1   
2           1       3                             Heikkinen, Miss. Laina    1   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1   
4           0       3                           Allen, Mr. William Henry    0   
..        ...     ...                                                ...  ...   
886         0       2                              Montvila, Rev. Juozas    0   
887         1       1                       Graham, Miss. Margaret Edith    1   
888         0       3           Johnston, Miss. Catherine Helen "Carrie"    1   
889         1       1                              Behr, Mr. Karl Howell    0   
890         0       3                                Dooley, Mr. Patrick    0   

      age  sibsp  parch            ticket     fare cabin  embarked_C  \
0    22.0      1      0         A/5 21171   7.2500   NaN       False   
1    38.0      1      0          PC 17599  71.2833   C85        True   
2    26.0      0      0  STON/O2. 3101282   7.9250   NaN       False   
3    35.0      1      0            113803  53.1000  C123       False   
4    35.0      0      0            373450   8.0500   NaN       False   
..    ...    ...    ...               ...      ...   ...         ...   
886  27.0      0      0            211536  13.0000   NaN       False   
887  19.0      0      0            112053  30.0000   B42       False   
888   NaN      1      2        W./C. 6607  23.4500   NaN       False   
889  26.0      0      0            111369  30.0000  C148        True   
890  32.0      0      0            370376   7.7500   NaN       False   

     embarked_Q  embarked_S  
0         False        True  
1         False       False  
2         False        True  
3         False        True  
4         False        True  
..          ...         ...  
886       False        True  
887       False        True  
888       False        True  
889       False       False  
890        True       False  

[891 rows x 13 columns]

In [12]:
ohe=OneHotEncoder(drop="first")

In [13]:
ohe.fit_transform(df[["embarked"]]).toarray()

array([[0., 1., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

NOTE:  last column is for null values.

In [14]:
ohe=OneHotEncoder(drop="first",sparse_output=False)  

NOTE:  if use sparse_output function with False value then we don't need to use toarray function.

In [15]:
ohe.fit_transform(df[["embarked"]])

array([[0., 1., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

remove or fill null values :

In [16]:
df["embarked"]=df["embarked"].fillna(df["embarked"].mode()[0]) 

In [17]:
ohe.fit_transform(df[["embarked"]])  #conver string in numeric

array([[0., 1.],
       [0., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 0.],
       [1., 0.]])

In [18]:
c=ohe.fit_transform(df[["embarked"]]) # store in variable

In [19]:
columns=ohe.get_feature_names_out() 

NOTE: give particuler column for values.

In [20]:
pd.DataFrame(c,columns=columns)

embarked_Q  embarked_S
0           0.0         1.0
1           0.0         0.0
2           0.0         1.0
3           0.0         1.0
4           0.0         1.0
..          ...         ...
886         0.0         1.0
887         0.0         1.0
888         0.0         1.0
889         0.0         0.0
890         1.0         0.0

[891 rows x 2 columns]