**importing library**

In [1]:
import numpy as np

In [2]:
 np.array(2,4,244,5,6)        #np.array(2, 4, 244, 5, 6) tries to pass five separate arguments, but np.array() only accepts:
                              #1st argument: the actual data (as an iterable),
                              #Optional 2nd argument: dtype, for specifying data type

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [3]:
np.array([2,4,245,4,6])

array([  2,   4, 245,   4,   6])

In [4]:
x=np.array([2,246,2,5,6])

In [5]:
x

array([  2, 246,   2,   5,   6])

In [6]:
y=np.array([[2,10],[3,20],[4,30]])

In [7]:
y

array([[ 2, 10],
       [ 3, 20],
       [ 4, 30]])

In [8]:
y.ndim

2

In [9]:
y.shape

(3, 2)

In [10]:
list1=[1,2,3,4]
list2=[5,6,7,8]  

In [11]:
np.array([list1,list2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
c=np.array([list1,list2])

In [13]:
c[1,3]

8

In [14]:
c[0,3]

4

In [15]:
x

array([  2, 246,   2,   5,   6])

In [16]:
x[1]

246

In [17]:
np.where(x==246)

(array([1], dtype=int64),)

In [18]:
np.where(x==244)

(array([], dtype=int64),)

In [19]:
np.isin(x,2)

array([ True, False,  True, False, False])

In [20]:
np.isin(x,2).sum()

2

In [21]:
np.ones(100,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
v=np.ones(10,dtype=int)

In [24]:
v

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
v.reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [26]:
v.reshape(2,5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
x.sum()

261

In [28]:
np.sum(x)

261

In [29]:
x.max()

246

In [30]:
x.min()

2

In [31]:
len(x)

5

In [32]:
x.std()

96.91315700151347

In [33]:
np.square(x)

array([    4, 60516,     4,    25,    36])

In [34]:
np.power(x,3)

array([       8, 14886936,        8,      125,      216], dtype=int32)

In [35]:
np.exp(x)

array([7.38905610e+000, 6.86187098e+106, 7.38905610e+000, 1.48413159e+002,
       4.03428793e+002])

In [36]:
np.sin(x)

array([ 0.90929743,  0.81676   ,  0.90929743, -0.95892427, -0.2794155 ])

In [37]:
np.insert(x,2,3)

array([  2, 246,   3,   2,   5,   6])

creating 2d array

In [38]:
arr_2d = np.array([[1,2,3],[4,5,6]])

In [39]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

np.zeros(shape): Creates an array of given shape filled with zeros.

In [40]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [42]:
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

np.ones(shape): Creates an array of given shape filled with ones.

In [44]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [45]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.arange(start, stop, step): Creates an array with a range of values.

In [46]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [47]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(1,26,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

np.linspace(start, stop, num): Creates an array with evenly spaced values over a specified range.

In [49]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [50]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [51]:
np.linspace(1,15,8)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15.])

np.eye(n): Creates an identity matrix of size n.

In [52]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [54]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Mathematical Operation

In [55]:
arr1 = np.array([1,2,3])

In [56]:
arr2 = np.array([4,5,6])

Element-wise addition :

In [57]:
print(arr1+arr2)

[5 7 9]


Element-wise multiplication :

In [58]:
print(arr1*arr2)

[ 4 10 18]


In [59]:
print(np.dot(arr1,arr2))

32


 Dot product : The dot product measures how much two vectors point in the same direction  OR
              returns the sum of the products of corresponding elements between two vectors (arrays of equal length)
             
 Output: 32  (1*4 + 2*5 + 3*6)

Broadcasting

In [60]:
arr1 = np.array([1,2,3])

In [61]:
arr2 = np.array([[1],[2],[3]])

Broadcasting addition :

In [62]:
print(arr1+arr2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


Broadcasting multipication : 

In [63]:
print(arr1*arr2)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [64]:
np.empty([2,2],dtype = float)

array([[1., 0.],
       [0., 1.]])